server:
  port: 8084

spring:
  application:
    name: auth-service

  datasource:
    url: ${AUTH_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET}
  expiration-ms-jwt-token: ${JWT_EXPIRATION_MS_JWT_TOKEN}
  expiration-ms-refresh-token: ${JWT_EXPIRATION_MS_REFRESH_TOKEN}
