services:

  # Gateway
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - order-flow-network
    depends_on:
      auth-frontend:
        condition: service_started
      order-frontend:
        condition: service_started
      delivery-frontend:
        condition: service_started
      auth-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
      payment-service:
        condition: service_healthy
      delivery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost/ || exit 1"]
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 5

  # Frontends

  auth-frontend:
    build:
      context: ./frontend
      dockerfile: auth-service-frontend/Dockerfile
    container_name: auth-frontend
    restart: unless-stopped
    networks:
      - order-flow-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost/ || exit 1"]
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 5

  order-frontend:
    build:
      context: ./frontend
      dockerfile: order-service-frontend/Dockerfile
    container_name: order-frontend
    restart: unless-stopped
    networks:
      - order-flow-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost/ || exit 1"]
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 5

  delivery-frontend:
    build:
      context: ./frontend
      dockerfile: delivery-service-frontend/Dockerfile
    container_name: delivery-frontend
    restart: unless-stopped
    networks:
      - order-flow-network
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost/ || exit 1" ]
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 5

  # Services

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    restart: unless-stopped

    ports:
      - "8081:8081"

    environment:
      - ORDER_DB_URL=jdbc:postgresql://order-db:5432/${ORDER_DB_NAME}
      - PAYMENT_SERVICE_URL=http://payment-service:8082
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - order-flow-network
    depends_on:
      order-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      payment-service:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      start_period: 40s
      retries: 5

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    restart: unless-stopped

    ports:
      - "8082:8082"

    environment:
      - PAYMENT_DB_URL=jdbc:postgresql://payment-db:5432/${PAYMENT_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - order-flow-network
    depends_on:
      payment-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 40s
      retries: 5

  delivery-service:
    build:
      context: .
      dockerfile: delivery-service/Dockerfile
    container_name: delivery-service
    restart: unless-stopped

    ports:
      - "8083:8083"

    environment:
      - DELIVERY_DB_URL=jdbc:postgresql://delivery-db:5432/${DELIVERY_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - order-flow-network
    depends_on:
      delivery-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8083/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      start_period: 40s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    restart: unless-stopped

    ports:
      - "8084:8084"

    environment:
      - AUTH_DB_URL=jdbc:postgresql://auth-db:5432/${AUTH_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_MS_JWT_TOKEN=${JWT_EXPIRATION_MS_JWT_TOKEN}
      - JWT_EXPIRATION_MS_REFRESH_TOKEN=${JWT_EXPIRATION_MS_REFRESH_TOKEN}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    networks:
      - order-flow-network
    depends_on:
      auth-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8084/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      start_period: 40s
      retries: 5

 # DB

  order-db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${ORDER_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${ORDER_DB_PORT}:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    networks:
      - order-flow-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${ORDER_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  payment-db:
    image: postgres:17-alpine
    container_name: payment-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PAYMENT_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PAYMENT_DB_PORT}:5432"
    volumes:
      - postgres_payment_data:/var/lib/postgresql/data
    networks:
      - order-flow-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${PAYMENT_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  delivery-db:
    image: postgres:17-alpine
    container_name: delivery-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DELIVERY_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DELIVERY_DB_PORT}:5432"
    volumes:
      - postgres_delivery_data:/var/lib/postgresql/data
    networks:
      - order-flow-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DELIVERY_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-db:
    image: postgres:17-alpine
    container_name: auth-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${AUTH_DB_PORT}:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - order-flow-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${AUTH_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - order-flow-network

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:8.1.1
    container_name: kafka-broker
    restart: unless-stopped
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - order-flow-network
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: order-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - order-flow-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  order-flow-network:
    driver: bridge
    name: order-flow-network

volumes:
  postgres_order_data:
  postgres_payment_data:
  postgres_delivery_data:
  postgres_auth_data:
  kafka_data:
  minio-data:
